/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RecursosRouteImport } from './routes/recursos'
import { Route as NosotrosRouteImport } from './routes/nosotros'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as DiplomadoRouteImport } from './routes/diplomado'
import { Route as DesarrolloHumanoIntegralRouteImport } from './routes/desarrollo-humano-integral'
import { Route as CursosGrabadosRouteImport } from './routes/cursos-grabados'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as CertificacionIiiRouteImport } from './routes/certificacion-iii'
import { Route as CertificacionIiRouteImport } from './routes/certificacion-ii'
import { Route as CertificacionIRouteImport } from './routes/certificacion-i'
import { Route as CentroDeConocimientoRouteImport } from './routes/centro-de-conocimiento'
import { Route as CampusVirtualRouteImport } from './routes/campus-virtual'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RecursosRoute = RecursosRouteImport.update({
  id: '/recursos',
  path: '/recursos',
  getParentRoute: () => rootRouteImport,
} as any)
const NosotrosRoute = NosotrosRouteImport.update({
  id: '/nosotros',
  path: '/nosotros',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const DiplomadoRoute = DiplomadoRouteImport.update({
  id: '/diplomado',
  path: '/diplomado',
  getParentRoute: () => rootRouteImport,
} as any)
const DesarrolloHumanoIntegralRoute =
  DesarrolloHumanoIntegralRouteImport.update({
    id: '/desarrollo-humano-integral',
    path: '/desarrollo-humano-integral',
    getParentRoute: () => rootRouteImport,
  } as any)
const CursosGrabadosRoute = CursosGrabadosRouteImport.update({
  id: '/cursos-grabados',
  path: '/cursos-grabados',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificacionIiiRoute = CertificacionIiiRouteImport.update({
  id: '/certificacion-iii',
  path: '/certificacion-iii',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificacionIiRoute = CertificacionIiRouteImport.update({
  id: '/certificacion-ii',
  path: '/certificacion-ii',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificacionIRoute = CertificacionIRouteImport.update({
  id: '/certificacion-i',
  path: '/certificacion-i',
  getParentRoute: () => rootRouteImport,
} as any)
const CentroDeConocimientoRoute = CentroDeConocimientoRouteImport.update({
  id: '/centro-de-conocimiento',
  path: '/centro-de-conocimiento',
  getParentRoute: () => rootRouteImport,
} as any)
const CampusVirtualRoute = CampusVirtualRouteImport.update({
  id: '/campus-virtual',
  path: '/campus-virtual',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/campus-virtual': typeof CampusVirtualRoute
  '/centro-de-conocimiento': typeof CentroDeConocimientoRoute
  '/certificacion-i': typeof CertificacionIRoute
  '/certificacion-ii': typeof CertificacionIiRoute
  '/certificacion-iii': typeof CertificacionIiiRoute
  '/contacto': typeof ContactoRoute
  '/cursos-grabados': typeof CursosGrabadosRoute
  '/desarrollo-humano-integral': typeof DesarrolloHumanoIntegralRoute
  '/diplomado': typeof DiplomadoRoute
  '/mcp': typeof McpRoute
  '/nosotros': typeof NosotrosRoute
  '/recursos': typeof RecursosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/campus-virtual': typeof CampusVirtualRoute
  '/centro-de-conocimiento': typeof CentroDeConocimientoRoute
  '/certificacion-i': typeof CertificacionIRoute
  '/certificacion-ii': typeof CertificacionIiRoute
  '/certificacion-iii': typeof CertificacionIiiRoute
  '/contacto': typeof ContactoRoute
  '/cursos-grabados': typeof CursosGrabadosRoute
  '/desarrollo-humano-integral': typeof DesarrolloHumanoIntegralRoute
  '/diplomado': typeof DiplomadoRoute
  '/mcp': typeof McpRoute
  '/nosotros': typeof NosotrosRoute
  '/recursos': typeof RecursosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/campus-virtual': typeof CampusVirtualRoute
  '/centro-de-conocimiento': typeof CentroDeConocimientoRoute
  '/certificacion-i': typeof CertificacionIRoute
  '/certificacion-ii': typeof CertificacionIiRoute
  '/certificacion-iii': typeof CertificacionIiiRoute
  '/contacto': typeof ContactoRoute
  '/cursos-grabados': typeof CursosGrabadosRoute
  '/desarrollo-humano-integral': typeof DesarrolloHumanoIntegralRoute
  '/diplomado': typeof DiplomadoRoute
  '/mcp': typeof McpRoute
  '/nosotros': typeof NosotrosRoute
  '/recursos': typeof RecursosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/campus-virtual'
    | '/centro-de-conocimiento'
    | '/certificacion-i'
    | '/certificacion-ii'
    | '/certificacion-iii'
    | '/contacto'
    | '/cursos-grabados'
    | '/desarrollo-humano-integral'
    | '/diplomado'
    | '/mcp'
    | '/nosotros'
    | '/recursos'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog'
    | '/campus-virtual'
    | '/centro-de-conocimiento'
    | '/certificacion-i'
    | '/certificacion-ii'
    | '/certificacion-iii'
    | '/contacto'
    | '/cursos-grabados'
    | '/desarrollo-humano-integral'
    | '/diplomado'
    | '/mcp'
    | '/nosotros'
    | '/recursos'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/.mcp/invoke-tool/$tool'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/campus-virtual'
    | '/centro-de-conocimiento'
    | '/certificacion-i'
    | '/certificacion-ii'
    | '/certificacion-iii'
    | '/contacto'
    | '/cursos-grabados'
    | '/desarrollo-humano-integral'
    | '/diplomado'
    | '/mcp'
    | '/nosotros'
    | '/recursos'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRoute
  CampusVirtualRoute: typeof CampusVirtualRoute
  CentroDeConocimientoRoute: typeof CentroDeConocimientoRoute
  CertificacionIRoute: typeof CertificacionIRoute
  CertificacionIiRoute: typeof CertificacionIiRoute
  CertificacionIiiRoute: typeof CertificacionIiiRoute
  ContactoRoute: typeof ContactoRoute
  CursosGrabadosRoute: typeof CursosGrabadosRoute
  DesarrolloHumanoIntegralRoute: typeof DesarrolloHumanoIntegralRoute
  DiplomadoRoute: typeof DiplomadoRoute
  McpRoute: typeof McpRoute
  NosotrosRoute: typeof NosotrosRoute
  RecursosRoute: typeof RecursosRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recursos': {
      id: '/recursos'
      path: '/recursos'
      fullPath: '/recursos'
      preLoaderRoute: typeof RecursosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nosotros': {
      id: '/nosotros'
      path: '/nosotros'
      fullPath: '/nosotros'
      preLoaderRoute: typeof NosotrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diplomado': {
      id: '/diplomado'
      path: '/diplomado'
      fullPath: '/diplomado'
      preLoaderRoute: typeof DiplomadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desarrollo-humano-integral': {
      id: '/desarrollo-humano-integral'
      path: '/desarrollo-humano-integral'
      fullPath: '/desarrollo-humano-integral'
      preLoaderRoute: typeof DesarrolloHumanoIntegralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cursos-grabados': {
      id: '/cursos-grabados'
      path: '/cursos-grabados'
      fullPath: '/cursos-grabados'
      preLoaderRoute: typeof CursosGrabadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificacion-iii': {
      id: '/certificacion-iii'
      path: '/certificacion-iii'
      fullPath: '/certificacion-iii'
      preLoaderRoute: typeof CertificacionIiiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificacion-ii': {
      id: '/certificacion-ii'
      path: '/certificacion-ii'
      fullPath: '/certificacion-ii'
      preLoaderRoute: typeof CertificacionIiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificacion-i': {
      id: '/certificacion-i'
      path: '/certificacion-i'
      fullPath: '/certificacion-i'
      preLoaderRoute: typeof CertificacionIRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/centro-de-conocimiento': {
      id: '/centro-de-conocimiento'
      path: '/centro-de-conocimiento'
      fullPath: '/centro-de-conocimiento'
      preLoaderRoute: typeof CentroDeConocimientoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campus-virtual': {
      id: '/campus-virtual'
      path: '/campus-virtual'
      fullPath: '/campus-virtual'
      preLoaderRoute: typeof CampusVirtualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRoute,
  CampusVirtualRoute: CampusVirtualRoute,
  CentroDeConocimientoRoute: CentroDeConocimientoRoute,
  CertificacionIRoute: CertificacionIRoute,
  CertificacionIiRoute: CertificacionIiRoute,
  CertificacionIiiRoute: CertificacionIiiRoute,
  ContactoRoute: ContactoRoute,
  CursosGrabadosRoute: CursosGrabadosRoute,
  DesarrolloHumanoIntegralRoute: DesarrolloHumanoIntegralRoute,
  DiplomadoRoute: DiplomadoRoute,
  McpRoute: McpRoute,
  NosotrosRoute: NosotrosRoute,
  RecursosRoute: RecursosRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
